### ISSUE TITLE
can not connect to /dev/ttyAMC1

### ISSUE THREAD

**Issue by hakaiderii** [RAKWireless/udp-packet-forwarder#13]
hi

if i write  in docker-compose.yml

  devices:
     - /dev/ttyACM1    

it alway look for dev/ttyACM0  but my concentrator connect to /dev/ttyACM1

![image](https://github.com/RAKWireless/udp-packet-forwarder/assets/38075885/5a6b9c3b-815a-4e26-a6c6-6ad9bdd234bd)

**Comment by xoseperez** [comment]
Hi @hakaiderii 
By adding `/dev/ttyACM1` to your `devices` section you are making it accesible to the container, but you still have to tell the service to use it instead of the default one using the `DEVICE` variable. It will be something like this:

```
devices:
  - /dev/ttyACM1
 environment:
  DEVICE: /dev/ttyACM1
```

Or you can mount the device to the default path **inside** the container:

```
devices:
  - /dev/ttyACM1:/dev/ttyACM0
```

Another option is to run in privileged mode, which means all devices in the host ara available to the container, but I guess this is what you are trying to avoid,

**Comment by xoseperez** [comment]
I'm closing this issue. Please feel free to reopen if you need further assistance.
